services:
  - type: web
    name: formflow-frontend
    runtime: static
    plan: free
    buildCommand: npm run build
    buildOutputPath: client/dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://srnzhlxmmljizohqlfce.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybnpobHhtbWxqaXpvaHFsZmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDA5NzYsImV4cCI6MjA4NTg3Njk3Nn0.KjCHJ9mTdvN5fq5fKgSF4b12IQ-Ajlgc3usXCAgeAQI
